const data = [
  {
    attempts: 2,
    avg_attempts_per_game: 2,
    avg_yards_per_attempt: 3.5,
    avg_yards_per_game: 7,
    first_down: 0,
    first_down_pct: 0,
    forty_plus_yards: 0,
    fumbles: 0,
    longest_rush: '7',
    name: 'Joe Banyard',
    position: 'RB',
    team: 'JAX',
    touchdowns: 0,
    twenty_plus_yards: 0,
    yards: 7,
  },
  {
    attempts: 5,
    avg_attempts_per_game: 1.7,
    avg_yards_per_attempt: 1,
    avg_yards_per_game: 1.7,
    first_down: 0,
    first_down_pct: 0,
    forty_plus_yards: 0,
    fumbles: 0,
    longest_rush: '9',
    name: 'Shaun Hill',
    position: 'QB',
    team: 'MIN',
    touchdowns: 0,
    twenty_plus_yards: 0,
    yards: 5,
  },
  {
    attempts: 1,
    avg_attempts_per_game: 0.1,
    avg_yards_per_attempt: 2,
    avg_yards_per_game: 0.1,
    first_down: 0,
    first_down_pct: 0,
    forty_plus_yards: 0,
    fumbles: 0,
    longest_rush: '2',
    name: 'Breshad Perriman',
    position: 'WR',
    team: 'BAL',
    touchdowns: 0,
    twenty_plus_yards: 0,
    yards: 2,
  },
  {
    attempts: 2,
    avg_attempts_per_game: 2,
    avg_yards_per_attempt: 0.5,
    avg_yards_per_game: 1,
    first_down: 0,
    first_down_pct: 0,
    forty_plus_yards: 0,
    fumbles: 0,
    longest_rush: '2',
    name: 'Charlie Whitehurst',
    position: 'QB',
    team: 'CLE',
    touchdowns: 0,
    twenty_plus_yards: 0,
    yards: 1,
  },
  {
    attempts: 9,
    avg_attempts_per_game: 0.7,
    avg_yards_per_attempt: 3.4,
    avg_yards_per_game: 2.4,
    first_down: 3,
    first_down_pct: 33.3,
    forty_plus_yards: 0,
    fumbles: 0,
    longest_rush: '10',
    name: 'Lance Dunbar',
    position: 'RB',
    team: 'DAL',
    touchdowns: 1,
    twenty_plus_yards: 0,
    yards: 31,
  },
  {
    attempts: 205,
    avg_attempts_per_game: 12.8,
    avg_yards_per_attempt: 5.1,
    avg_yards_per_game: 65.2,
    first_down: 49,
    first_down_pct: 23.9,
    forty_plus_yards: 2,
    fumbles: 2,
    longest_rush: '75T',
    name: 'Mark Ingram',
    position: 'RB',
    team: 'NO',
    touchdowns: 6,
    twenty_plus_yards: 4,
    yards: '1,043',
  },
  {
    attempts: 12,
    avg_attempts_per_game: 0.9,
    avg_yards_per_attempt: -0.3,
    avg_yards_per_game: -0.2,
    first_down: 2,
    first_down_pct: 16.7,
    forty_plus_yards: 0,
    fumbles: 1,
    longest_rush: 5,
    name: 'Reggie Bush',
    position: 'RB',
    team: 'BUF',
    touchdowns: 1,
    twenty_plus_yards: 0,
    yards: -3,
  },
  {
    attempts: 10,
    avg_attempts_per_game: 0.7,
    avg_yards_per_attempt: 8.2,
    avg_yards_per_game: 5.5,
    first_down: 4,
    first_down_pct: 40,
    forty_plus_yards: 0,
    fumbles: 1,
    longest_rush: '26',
    name: 'Lucky Whitehead',
    position: 'WR',
    team: 'DAL',
    touchdowns: 0,
    twenty_plus_yards: 1,
    yards: 82,
  },
  {
    attempts: 3,
    avg_attempts_per_game: 0.8,
    avg_yards_per_attempt: -0.7,
    avg_yards_per_game: -0.5,
    first_down: 0,
    first_down_pct: 0,
    forty_plus_yards: 0,
    fumbles: 1,
    longest_rush: 0,
    name: 'Brett Hundley',
    position: 'QB',
    team: 'GB',
    touchdowns: 0,
    twenty_plus_yards: 0,
    yards: -2,
  },
  {
    attempts: 24,
    avg_attempts_per_game: 1.5,
    avg_yards_per_attempt: 11.1,
    avg_yards_per_game: 16.7,
    first_down: 10,
    first_down_pct: 41.7,
    forty_plus_yards: 2,
    fumbles: 0,
    longest_rush: '70T',
    name: 'Tyreek Hill',
    position: 'WR',
    team: 'KC',
    touchdowns: 3,
    twenty_plus_yards: 4,
    yards: 267,
  },
  {
    attempts: 10,
    avg_attempts_per_game: 0.8,
    avg_yards_per_attempt: 3.3,
    avg_yards_per_game: 2.5,
    first_down: 4,
    first_down_pct: 40,
    forty_plus_yards: 0,
    fumbles: 0,
    longest_rush: '14',
    name: 'Randall Cobb',
    position: 'WR',
    team: 'GB',
    touchdowns: 0,
    twenty_plus_yards: 0,
    yards: 33,
  },
  {
    attempts: 34,
    avg_attempts_per_game: 2.1,
    avg_yards_per_attempt: 4.4,
    avg_yards_per_game: 9.4,
    first_down: 10,
    first_down_pct: 29.4,
    forty_plus_yards: 0,
    fumbles: 0,
    longest_rush: '15',
    name: 'Aaron Ripkowski',
    position: 'FB',
    team: 'GB',
    touchdowns: 2,
    twenty_plus_yards: 0,
    yards: 150,
  },
]

export async function getRushings(sortings, filter) {
  console.log(sortings)
  console.log(filter)
  return await data
}
